version: "{build}"

os: Visual Studio 2017
platform:
  - x64

cache:
  - vendor/bundle

environment:
  matrix:
    - ruby_version: "24-x64"
    - ruby_version: "24"

clone_folder: c:\projects\chefdk
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - systeminfo
  - winrm quickconfig -q
  - regedit /s c:\projects\chefdk\appveyor_registry.reg
  - SET FORCE_FFI_YAJL=ext
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - SET BUNDLE_WITHOUT=guard:maintenance:tools:integration:changelog:docgen:travis:style:omnibus_package:aix:bsd:linux:mac_os_x:solaris
  - bundle config --local path vendor/bundle # use the cache we define above
  - bundle install || bundle install || bundle install

build: off

before_test:
  - ruby --version
  - gem --version
  - bundler --version
  - bundle env

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rspec
